### ISSUE TITLE
Suggestion: Create releases

### ISSUE THREAD

**Issue by Steb03** [ScratchLang/ScratchLang#7]
**Is your feature request related to a problem? Please describe.**
Current version number is in the README

**Describe the solution you'd like**
Make releases, which are wayy better

**Describe alternatives you've considered**
Keep on making it in the README

**Additional context**

**Comment by Nonethousand** [comment]
Next version of ScratchLang, the version will be in the release instead of the readme

**Comment by Steb03** [comment]
Ok!
