### ISSUE TITLE
Syntax Suggestions

### ISSUE THREAD

**Issue by wendiner** [ScratchLang/ScratchLang#8]
I think we should use more standard syntax for list and variable declarations/definitions.
Instead of **list: foo="item1", "item2", "item3"**, why not **list foo = {"item1", "item2", "item3"}**?
And which keywords should we use for scoping?
*public/private*, *shared/unshared*, *global/local*, *var/let*, *all/self*?

What function do **\nscript** and **\prep** serve?

Does ScratchLang support commenting? If so, how should that work?
Based on the shebang section, I'd assume that "//" is the token of choice.
If that's the case, then it should be explicitly mentioned somewhere in the README/documentation.

**Comment by Nonethousand** [comment]
The things after the \prep line are what the compiler uses to define variables, broadcasts, and lists. the \nscript line tells the compiler that it is a new script (like a green flag or broadcast receive.)

I am thinking of changing it from a '\' to a '#' to make it look like a C++ preprocessor definition or something.

for the lists, I have no idea why I made it without the curly braces.

And if I'm understanding your scoping question correctly, you use var: foo=thing in the \prep section to define a variable to be used in the .ss1 file. Variables that will be available for all sprites will be defined in the Stage, but sprite-exclusive variables will be defined in their respective .ss1 files.

and yes, comments are supported with "//"
